baseURL = 'http://nsivkov.com/'
languageCode = 'en-us'
title = "A dev's ramblings on things"
theme = 'hugo-theme-stack'

# config.toml
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"